# Google Models ##############################################
gemini-1.5-pro:
  provider: google
  params:
    model: gemini-1.5-pro

gemini-1.5-flash:
  provider: google
  params:
    model: gemini-1.5-flash

gemini-1.0-pro:
  provider: google
  params:
    model: gemini-1.0-pro

# OpenAI Models ##############################################
gpt-4o:
  provider: openai
  params:
    model_name: gpt-4o

gpt-4-turbo:
  provider: openai
  params:
    model_name: gpt-4-turbo

gpt-4:
  provider: openai
  params:
    model_name: gpt-4

gpt-3.5-turbo:
  provider: openai
  params:
    model_name: ggpt-3.5-turbo

dall-e-3:
  provider: openai
  params:
    model_name: dall-e-3

dall-e-2:
  provider: openai
  params:
    model_name: dall-e-2

tts-1:
  provider: openai
  params:
    model_name: tts-1

tts-1-hd:
  provider: openai
  params:
    model_name: tts-1-hd

whisper-1:
  provider: openai
  params:
    model_name: whisper-1

# Anthropic Models ##############################################
claude-3.5-sonnet:
  provider: anthropic
  params:
    model: claude-3-5-sonnet-20240620

claude-3-opus:
  provider: anthropic
  params:
    model: claude-3-opus-20240229

claude-3-sonnet:
  provider: anthropic
  params:
    model: claude-3-sonnet-20240229

claude-3-haiku:
  provider: anthropic
  params:
    model: claude-3-haiku-20240307

# Groq Models ##############################################
groq-llama3-8b-8k:
  provider: groq
  params:
    model_name: llama3-8b-8192
    max_tokens: 8192

groq-llama3-70b-8k:
  provider: groq
  params:
    model_name: llama3-8b-8192
    max_tokens: 8192

groq-mixtral-8x7b:
  provider: groq
  params:
    model_name: mixtral-8x7b-32768
    max_tokens: 32768

groq-gemma-7b-8k:
  provider: groq
  params:
    model_name: gemma-7b-it
    max_tokens: 8192

groq-whisper-large-v3:
  provider: groq
  params:
    model_name: whisper-large-v3

# Ollama Models ##############################################
o-phi3-14b-128k-fp16:
  provider: ollama
  params:
    model: phi3:14b-medium-128k-instruct-f16
    num_ctx: 131072

o-phi3-14b-128k-q6:
  provider: ollama
  params:
    model: phi3:14b-medium-128k-instruct-q6_K
    num_ctx: 131072

o-phi3-14b-128k-q4:
  provider: ollama
  params:
    model: phi3:14b-medium-128k-instruct-q4_K_M
    num_ctx: 131072

o-phi3-14b-128k-q2:
  provider: ollama
  params:
    model: phi3:14b-medium-128k-instruct-q2_K
    num_ctx: 131072

o-phi3-14b-4k-fp16:
  provider: ollama
  params:
    model: phi3:14b-medium-4k-instruct-f16

o-phi3-14b-4k-q8:
  provider: ollama
  params:
    model: phi3:14b-medium-4k-instruct-q8_0

o-phi3-14b-4k-q6:
  provider: ollama
  params:
    model: phi3:14b-medium-4k-instruct-q6_K

o-phi3-14b-4k-q4:
  provider: ollama
  params:
    model: phi3:14b-medium-4k-instruct-q4_K_M

o-phi3-14b-4k-q2:
  provider: ollama
  params:
    model: phi3:14b-medium-4k-instruct-q2_K

o-phi3-8b-128k-fp16:
  provider: ollama
  params:
    model: phi3:3.8b-mini-128k-instruct-f16
    num_ctx: 131072

o-phi3-8b-128k-q8:
  provider: ollama
  params:
    model: phi3:3.8b-mini-128k-instruct-q8_0
    num_ctx: 131072

o-phi3-8b-128k-q4:
  provider: ollama
  params:
    model: phi3:3.8b-mini-128k-instruct-q4_1
    num_ctx: 131072

o-phi3-8b-128k-q2:
  provider: ollama
  params:
    model: phi3:3.8b-mini-128k-instruct-q2_K
    num_ctx: 131072

o-phi3-3b-4k-fp16:
  provider: ollama
  params:
    model: phi3:3.8b-mini-4k-instruct-f16

o-phi3-3b-4k-q8:
  provider: ollama
  params:
    model: phi3:3.8b-mini-4k-instruct-q8_0

o-phi3-3b-4k-q4:
  provider: ollama
  params:
    model: phi3:3.8b-mini-4k-instruct-q4_1

o-phi3-3b-4k-q2:
  provider: ollama
  params:
    model: phi3:3.8b-mini-4k-instruct-q2_K

o-qwn2-72b-128k-fp16:
  provider: ollama
  params:
    model: qwen2:72b-instruct-fp16
    num_ctx: 131072

o-qwn2-72b-128k-q8:
  provider: ollama
  params:
    model: qwen2:72b-instruct-q8_0
    num_ctx: 131072

o-qwn2-72b-128k-q6:
  provider: ollama
  params:
    model: qwen2:72b-instruct-q6_K
    num_ctx: 131072

o-qwn2-72b-128k-q4:
  provider: ollama
  params:
    model: qwen2:72b-instruct-q4_K_M
    num_ctx: 131072

o-qwn2-72b-128k-q2:
  provider: ollama
  params:
    model: qwen2:72b-instruct-q2_K
    num_ctx: 131072

o-qwn2-7b-128k-fp16:
  provider: ollama
  params:
    model: qwen2:7b-instruct-fp16
    num_ctx: 131072

o-qwn2-7b-128k-q8:
  provider: ollama
  params:
    model: qwen2:7b-instruct-q8_0
    num_ctx: 131072

o-qwn2-7b-128k-q6:
  provider: ollama
  params:
    model: qwen2:7b-instruct-q6_K
    num_ctx: 131072

o-qwn2-7b-128k-q4:
  provider: ollama
  params:
    model: qwen2:7b-instruct-q4_0
    num_ctx: 131072

o-qwn2-7b-128k-q2:
  provider: ollama
  params:
    model: qwen2:7b-instruct-q2_K
    num_ctx: 131072

o-qwn2-2b-32k-fp16:
  provider: ollama
  params:
    model: qwen2:1.5b-instruct-fp16
    num_ctx: 32768

o-qwn2-2b-32k-q8:
  provider: ollama
  params:
    model: qwen2:1.5b-instruct-q8_0
    num_ctx: 32768

o-qwn2-2b-32k-q6:
  provider: ollama
  params:
    model: qwen2:1.5b-instruct-q6_K
    num_ctx: 32768

o-qwn2-2b-32k-q4:
  provider: ollama
  params:
    model: qwen2:1.5b-instruct-q4_0
    num_ctx: 32768

o-qwn2-2b-32k-q2:
  provider: ollama
  params:
    model: qwen2:1.5b-instruct-q2_K
    num_ctx: 32768

o-qwn2-1b-32k-fp16:
  provider: ollama
  params:
    model: qwen2:0.5b-instruct-fp16
    num_ctx: 32768

o-qwn2-1b-32k-q8:
  provider: ollama
  params:
    model: qwen2:0.5b-instruct-q8_0
    num_ctx: 32768

o-qwn2-1b-32k-q6:
  provider: ollama
  params:
    model: qwen2:0.5b-instruct-q6_K
    num_ctx: 32768

o-qwn2-1b-32k-q4:
  provider: ollama
  params:
    model: qwen2:0.5b-instruct-q4_0
    num_ctx: 32768

o-qwn2-1b-32k-q2:
  provider: ollama
  params:
    model: qwen2:0.5b-instruct-q2_K
    num_ctx: 32768

o-lma3-70b-8k-fp16:
  provider: ollama
  params:
    model: llama3:70b-instruct-fp16
    num_ctx: 8192

o-lma3-70b-8k-q8:
  provider: ollama
  params:
    model: llama3:70b-instruct-q8_0
    num_ctx: 8192

o-lma3-70b-8k-q6:
  provider: ollama
  params:
    model: llama3:70b-instruct-q6_K
    num_ctx: 8192

o-lma3-70b-8k-q4:
  provider: ollama
  params:
    model: llama3:70b-instruct-q4_0
    num_ctx: 8192

o-lma3-70b-8k-q2:
  provider: ollama
  params:
    model: llama3:70b-instruct-q2_K
    num_ctx: 8192

o-lma3-8b-8k-fp16:
  provider: ollama
  params:
    model: llama3:8b-instruct-fp16
    num_ctx: 8192

o-lma3-8b-8k-q8:
  provider: ollama
  params:
    model: llama3:8b-instruct-q8_0
    num_ctx: 8192

o-lma3-8b-8k-q6:
  provider: ollama
  params:
    model: llama3:8b-instruct-q6_K
    num_ctx: 8192

o-lma3-8b-8k-q4:
  provider: ollama
  params:
    model: llama3:8b-instruct-q4_0
    num_ctx: 8192

o-lma3-8b-8k-q2:
  provider: ollama
  params:
    model: llama3:8b-instruct-q2_K
    num_ctx: 8192


o-mis-7b-32k-fp16:
  provider: ollama
  params:
    model: mistral:7b-instruct-v0.3-fp16
    num_ctx: 32768

o-mis-7b-32k-q8:
  provider: ollama
  params:
    model: mistral:7b-instruct-v0.3-q8_0
    num_ctx: 32768

o-mis-7b-32k-q6:
  provider: ollama
  params:
    model: mistral:7b-instruct-v0.3-q6_K
    num_ctx: 32768

o-mis-7b-32k-q4:
  provider: ollama
  params:
    model: mistral:7b-instruct-v0.3-q4_0
    num_ctx: 32768

o-mis-7b-32k-q2:
  provider: ollama
  params:
    model: mistral:7b-instruct-v0.3-q2_K
    num_ctx: 32768


o-mix-8x22b-64k-fp16:
  provider: ollama
  params:
    model: mixtral:8x22b-instruct-v0.1-fp16
    num_ctx: 65536

o-mix-8x22b-64k-q8:
  provider: ollama
  params:
    model: mixtral:8x22b-instruct-v0.1-q8_0
    num_ctx: 65536

o-mix-8x22b-64k-q6:
  provider: ollama
  params:
    model: mixtral:8x22b-instruct-v0.1-q6_K
    num_ctx: 65536

o-mix-8x22b-64k-q4:
  provider: ollama
  params:
    model: mixtral:8x22b-instruct-v0.1-q4_0
    num_ctx: 65536

o-mix-8x22b-64k-q2:
  provider: ollama
  params:
    model: mixtral:8x22b-instruct-v0.1-q2_K
    num_ctx: 65536

o-mix-8x7b-32k-fp16:
  provider: ollama
  params:
    model: mixtral:8x7b-instruct-v0.1-fp16
    num_ctx: 32768

o-mix-8x7b-32k-q8:
  provider: ollama
  params:
    model: mixtral:8x7b-instruct-v0.1-q8_0
    num_ctx: 32768

o-mix-8x7b-32k-q6:
  provider: ollama
  params:
    model: mixtral:8x7b-instruct-v0.1-q6_K
    num_ctx: 32768

o-mix-8x7b-32k-q4:
  provider: ollama
  params:
    model: mixtral:8x7b-instruct-v0.1-q4_0
    num_ctx: 32768

o-mix-8x7b-32k-q2:
  provider: ollama
  params:
    model: mixtral:8x7b-instruct-v0.1-q2_K
    num_ctx: 32768


o-gma-7b-8k-fp16:
  provider: ollama
  params:
    model: gemma:7b-instruct-v1.1-fp16
    num_ctx: 8192

o-gma-7b-8k-q8:
  provider: ollama
  params:
    model: gemma:7b-instruct-v1.1-q8_0
    num_ctx: 8192

o-gma-7b-8k-q6:
  provider: ollama
  params:
    model: gemma:7b-instruct-v1.1-q6_K
    num_ctx: 8192

o-gma-7b-8k-q4:
  provider: ollama
  params:
    model: gemma:7b-instruct-v1.1-q4_0
    num_ctx: 8192

o-gma-7b-8k-q2:
  provider: ollama
  params:
    model: gemma:7b-instruct-v1.1-q2_K
    num_ctx: 8192

o-gma-2b-8k-fp16:
  provider: ollama
  params:
    model: gemma:2b-instruct-v1.1-fp16
    num_ctx: 8192

o-gma-2b-8k-q8:
  provider: ollama
  params:
    model: gemma:2b-instruct-v1.1-q8_0
    num_ctx: 8192

o-gma-2b-8k-q6:
  provider: ollama
  params:
    model: gemma:2b-instruct-v1.1-q6_K
    num_ctx: 8192

o-gma-2b-8k-q4:
  provider: ollama
  params:
    model: gemma:2b-instruct-v1.1-q4_0
    num_ctx: 8192

o-gma-2b-8k-q2:
  provider: ollama
  params:
    model: gemma:2b-instruct-v1.1-q2_K
    num_ctx: 8192


o-wizlm2-8x22b-64k-fp16:
  provider: ollama
  params:
    model: wizardlm2:8x22b-fp16
    num_ctx: 65536

o-wizlm2-8x22b-64k-q8:
  provider: ollama
  params:
    model: wizardlm2:8x22b-q8_0
    num_ctx: 65536

o-wizlm2-8x22b-64k-q4:
  provider: ollama
  params:
    model: wizardlm2:8x22b-q4_0
    num_ctx: 65536

o-wizlm2-8x22b-64k-q2:
  provider: ollama
  params:
    model: wizardlm2:8x22b-q2_K
    num_ctx: 65536

o-wizlm2-7b-32k-fp16:
  provider: ollama
  params:
    model: wizardlm2:7b-fp16
    num_ctx: 32768

o-wizlm2-7b-32k-q8:
  provider: ollama
  params:
    model: wizardlm2:7b-q8_0
    num_ctx: 32768

o-wizlm2-7b-32k-q6:
  provider: ollama
  params:
    model: wizardlm2:7b-q6_K
    num_ctx: 32768

o-wizlm2-7b-32k-q4:
  provider: ollama
  params:
    model: wizardlm2:7b-q4_0
    num_ctx: 32768

o-wizlm2-7b-32k-q2:
  provider: ollama
  params:
    model: wizardlm2:7b-q2_K
    num_ctx: 32768


o-cstral-22b-32k-fp16:
  provider: ollama
  params:
    model: codestral:22b-v0.1-f16
    num_ctx: 32768

o-cstral-22b-32k-q8:
  provider: ollama
  params:
    model: codestral:22b-v0.1-q8_0
    num_ctx: 32768

o-cstral-22b-32k-q6:
  provider: ollama
  params:
    model: codestral:22b-v0.1-q6_K
    num_ctx: 32768

o-cstral-22b-32k-q4:
  provider: ollama
  params:
    model: codestral:22b-v0.1-q4_0
    num_ctx: 32768

o-cstral-22b-32k-q2:
  provider: ollama
  params:
    model: codestral:22b-v0.1-q2_K
    num_ctx: 32768


o-lva-8b-32k-fp16:
  provider: ollama
  params:
    model: llava-llama3:8b-v1.1-fp16
    num_ctx: 32768

o-lva-8b-32k-q4:
  provider: ollama
  params:
    model: llava-llama3:8b-v1.1-q4_0
    num_ctx: 32768


o-l3g-70b-1m-fp16:
  provider: ollama
  params:
    model: llama3-gradient:70b-instruct-1048k-fp16
    num_ctx: 1042000

o-l3g-70b-1m-q8:
  provider: ollama
  params:
    model: llama3-gradient:70b-instruct-1048k-q8_0
    num_ctx: 1042000

o-l3g-70b-1m-q6:
  provider: ollama
  params:
    model: llama3-gradient:70b-instruct-1048k-q6_K
    num_ctx: 1042000

o-l3g-70b-1m-q4:
  provider: ollama
  params:
    model: llama3-gradient:70b-instruct-1048k-q4_0
    num_ctx: 1042000

o-l3g-70b-1m-q2:
  provider: ollama
  params:
    model: llama3-gradient:70b-instruct-1048k-q2_K
    num_ctx: 1042000


o-lvaphi3-3b-4k-fp16:
  provider: ollama
  params:
    model: llava-phi3:3.8b-mini-fp16
    num_ctx: 4092

o-lvaphi3-3b-4k-q4:
  provider: ollama
  params:
    model: llava-phi3:3.8b-mini-q4_0
    num_ctx: 4092


o-cgma-7b-8k-fp16:
  provider: ollama
  params:
    model: codegemma:7b-code-fp16
    num_ctx: 8192

o-cgma-7b-8k-q8:
  provider: ollama
  params:
    model: codegemma:7b-code-q8_0
    num_ctx: 8192

o-cgma-7b-8k-q6:
  provider: ollama
  params:
    model: codegemma:7b-code-q6_K
    num_ctx: 8192

o-cgma-7b-8k-q4:
  provider: ollama
  params:
    model: codegemma:7b-code-q4_0
    num_ctx: 8192

o-cgma-7b-8k-q2:
  provider: ollama
  params:
    model: codegemma:7b-code-q2_K
    num_ctx: 8192


o-cmd-r-35b-128k-fp16:
  provider: ollama
  params:
    model: command-r:35b-v0.1-fp16
    num_ctx: 131072

o-cmd-r-35b-128k-q8:
  provider: ollama
  params:
    model: command-r:35b-v0.1-q8_0
    num_ctx: 131072

o-cmd-r-35b-128k-q6:
  provider: ollama
  params:
    model: command-r:35b-v0.1-q6_K
    num_ctx: 131072

o-cmd-r-35b-128k-q4:
  provider: ollama
  params:
    model: command-r:35b-v0.1-q4_0
    num_ctx: 131072

o-cmd-r-35b-128k-q2:
  provider: ollama
  params:
    model: command-r:35b-v0.1-q2_K
    num_ctx: 131072


o-cmd-rp-104b-128k-fp16:
  provider: ollama
  params:
    model: command-r-plus:104b-fp16
    num_ctx: 131072

o-cmd-rp-104b-128k-q8:
  provider: ollama
  params:
    model: command-r-plus:104b-q8_0
    num_ctx: 131072

o-cmd-rp-104b-128k-q4:
  provider: ollama
  params:
    model: command-r-plus:104b-q4_0
    num_ctx: 131072

o-cmd-rp-104b-128k-q2:
  provider: ollama
  params:
    model: command-r-plus:104b-q2_K
    num_ctx: 131072


o-lva-34b-4k-fp16:
  provider: ollama
  params:
    model: llava:34b-v1.6-fp16
    num_ctx: 4096

o-lva-34b-4k-q8:
  provider: ollama
  params:
    model: llava:34b-v1.6-q8_0
    num_ctx: 4096

o-lva-34b-4k-q6:
  provider: ollama
  params:
    model: llava:34b-v1.6-q6_K
    num_ctx: 4096

o-lva-34b-4k-q4:
  provider: ollama
  params:
    model: llava:34b-v1.6-q4_0
    num_ctx: 4096

o-lva-34b-4k-q2:
  provider: ollama
  params:
    model: llava:34b-v1.6-q2_K
    num_ctx: 4096

o-lva-13b-4k-fp16:
  provider: ollama
  params:
    model: llava:13b-v1.6-vicuna-fp16
    num_ctx: 4096

o-lva-13b-4k-q8:
  provider: ollama
  params:
    model: llava:13b-v1.6-vicuna-q8_0
    num_ctx: 4096

o-lva-13b-4k-q6:
  provider: ollama
  params:
    model: llava:13b-v1.6-vicuna-q6_K
    num_ctx: 4096

o-lva-13b-4k-q4:
  provider: ollama
  params:
    model: llava:13b-v1.6-vicuna-q4_0
    num_ctx: 4096

o-lva-13b-4k-q2:
  provider: ollama
  params:
    model: llava:13b-v1.6-vicuna-q2_K
    num_ctx: 4096

o-lva-7b-4k-fp16:
  provider: ollama
  params:
    model: llava:7b-v1.6-vicuna-fp16
    num_ctx: 4096

o-lva-7b-4k-q8:
  provider: ollama
  params:
    model: llava:7b-v1.6-vicuna-q8_0
    num_ctx: 4096

o-lva-7b-4k-q6:
  provider: ollama
  params:
    model: llava:7b-v1.6-vicuna-q6_K
    num_ctx: 4096

o-lva-7b-4k-q4:
  provider: ollama
  params:
    model: llava:7b-v1.6-vicuna-q4_0
    num_ctx: 4096

o-lva-7b-4k-q2:
  provider: ollama
  params:
    model: llava:7b-v1.6-vicuna-q2_K
    num_ctx: 4096


o-dbrx-132b-32k-fp16:
  provider: ollama
  params:
    model: dbrx:132b-instruct-fp16
    num_ctx: 32768

o-dbrx-132b-32k-q8:
  provider: ollama
  params:
    model: dbrx:132b-instruct-q8_0
    num_ctx: 32768

o-dbrx-132b-32k-q4:
  provider: ollama
  params:
    model: dbrx:132b-instruct-q4_0
    num_ctx: 32768

o-dbrx-132b-32k-q2:
  provider: ollama
  params:
    model: dbrx:132b-instruct-q2_K
    num_ctx: 32768



# HuggingFace Models ##############################################
flan-t5-xxl:
  provider: huggingface
  params:
    repo_id: google/flan-t5-xxl
    max_new_tokens: 512
